-- 文档维护：Claude Opus 4.8（最近更新 2026-06-02）
-- BigQuery Standard SQL
-- OQ-003 财务三大报表 DWD（income/balancesheet/cashflow + 各自 _latest）与
-- dws_stock_feature_fin_daily 的表级 + 字段级中文说明补齐脚本。
-- 用法：财务 DWD/DWS 表（sql/dwd/06-11、sql/dws/07）CREATE OR REPLACE 重建后执行本脚本，
-- 集中恢复字段 description（CTAS 不保留列描述，PRD_20260601_03 §10 要求字段说明补齐）。
-- 覆盖完整性由 sql/qa/04_finance_caliber_checks.sql 的 description 缺失断言守卫。

-- ============================================================
-- dwd_fin_income（利润表版本事实表，金额单位元、累计/YTD）
-- ============================================================
ALTER TABLE `data-aquarium.ashare_dwd.dwd_fin_income`
ALTER COLUMN sec_code SET OPTIONS (description = '证券代码，Tushare ts_code 格式'),
ALTER COLUMN ann_date_eff SET OPTIONS (description = '公告生效日（可见日），COALESCE(f_ann_date, ann_date)，月分区字段'),
ALTER COLUMN report_period SET OPTIONS (description = '报告期，来自 end_date'),
ALTER COLUMN ann_date SET OPTIONS (description = '原始公告日，YYYYMMDD 字符串'),
ALTER COLUMN f_ann_date SET OPTIONS (description = '实际披露/最终公告日，YYYYMMDD 字符串；优先用于 ann_date_eff'),
ALTER COLUMN end_date SET OPTIONS (description = '报告期 YYYYMMDD 字符串原值'),
ALTER COLUMN report_type SET OPTIONS (description = 'Tushare 源报表类型编码，原样保留；1=合并报表（P0 默认消费口径）。实测当前仅 1'),
ALTER COLUMN comp_type SET OPTIONS (description = 'Tushare 公司类型：1 一般工商业 2 银行 3 保险 4 证券 等，决定报表模板'),
ALTER COLUMN update_flag SET OPTIONS (description = 'Tushare 更新标志，同公告时间下优先保留修正版'),
ALTER COLUMN basic_eps SET OPTIONS (description = '基本每股收益，元/股'),
ALTER COLUMN diluted_eps SET OPTIONS (description = '稀释每股收益，元/股'),
ALTER COLUMN total_revenue SET OPTIONS (description = '营业总收入，元，累计/YTD'),
ALTER COLUMN revenue SET OPTIONS (description = '营业收入，元，累计/YTD'),
ALTER COLUMN total_cogs SET OPTIONS (description = '营业总成本，元，累计/YTD'),
ALTER COLUMN oper_cost SET OPTIONS (description = '营业成本，元，累计/YTD'),
ALTER COLUMN sell_exp SET OPTIONS (description = '销售费用，元，累计/YTD'),
ALTER COLUMN admin_exp SET OPTIONS (description = '管理费用，元，累计/YTD'),
ALTER COLUMN fin_exp SET OPTIONS (description = '财务费用，元，累计/YTD'),
ALTER COLUMN rd_exp SET OPTIONS (description = '研发费用，元，累计/YTD'),
ALTER COLUMN operate_profit SET OPTIONS (description = '营业利润，元，累计/YTD'),
ALTER COLUMN non_oper_income SET OPTIONS (description = '营业外收入，元，累计/YTD'),
ALTER COLUMN non_oper_exp SET OPTIONS (description = '营业外支出，元，累计/YTD'),
ALTER COLUMN total_profit SET OPTIONS (description = '利润总额，元，累计/YTD'),
ALTER COLUMN income_tax SET OPTIONS (description = '所得税费用，元，累计/YTD'),
ALTER COLUMN n_income SET OPTIONS (description = '净利润（含少数股东损益），元，累计/YTD'),
ALTER COLUMN n_income_attr_p SET OPTIONS (description = '归属于母公司股东的净利润，元，累计/YTD'),
ALTER COLUMN minority_gain SET OPTIONS (description = '少数股东损益，元，累计/YTD'),
ALTER COLUMN ebit SET OPTIONS (description = '息税前利润，元，累计/YTD'),
ALTER COLUMN ebitda SET OPTIONS (description = '息税折旧摊销前利润，元，累计/YTD'),
ALTER COLUMN source_system SET OPTIONS (description = '来源系统标识，当前 tushare'),
ALTER COLUMN source_partition_date SET OPTIONS (description = '来源 ODS 分区（报告期），YYYYMMDD 字符串'),
ALTER COLUMN ingested_at SET OPTIONS (description = '来源 ODS 摄入时间'),
ALTER COLUMN report_caliber SET OPTIONS (description = '规范化口径：consolidated/non_consolidated/other/unknown；report_type IS NULL 时为 unknown'),
ALTER COLUMN is_default_report_caliber SET OPTIONS (description = '是否 P0 默认消费口径，等价于 COALESCE(report_type=1, FALSE)'),
ALTER COLUMN visible_trade_date SET OPTIONS (description = '公告生效日之后第一个上交所开市日，用于 PIT as-of join');

-- ============================================================
-- dwd_fin_income_latest（默认合并口径最新便捷表，列同事实表）
-- ============================================================
ALTER TABLE `data-aquarium.ashare_dwd.dwd_fin_income_latest`
ALTER COLUMN sec_code SET OPTIONS (description = '证券代码，Tushare ts_code 格式'),
ALTER COLUMN ann_date_eff SET OPTIONS (description = '该报告期默认口径最新版本的公告生效日'),
ALTER COLUMN report_period SET OPTIONS (description = '报告期，(sec_code, report_period) 唯一'),
ALTER COLUMN ann_date SET OPTIONS (description = '原始公告日，YYYYMMDD 字符串'),
ALTER COLUMN f_ann_date SET OPTIONS (description = '实际披露/最终公告日，YYYYMMDD 字符串'),
ALTER COLUMN end_date SET OPTIONS (description = '报告期 YYYYMMDD 字符串原值'),
ALTER COLUMN report_type SET OPTIONS (description = 'Tushare 源报表类型编码，本表恒为 1（合并报表）'),
ALTER COLUMN comp_type SET OPTIONS (description = 'Tushare 公司类型：1 一般工商业 2 银行 3 保险 4 证券 等'),
ALTER COLUMN update_flag SET OPTIONS (description = 'Tushare 更新标志，该报告期取最新修正版'),
ALTER COLUMN basic_eps SET OPTIONS (description = '基本每股收益，元/股'),
ALTER COLUMN diluted_eps SET OPTIONS (description = '稀释每股收益，元/股'),
ALTER COLUMN total_revenue SET OPTIONS (description = '营业总收入，元，累计/YTD'),
ALTER COLUMN revenue SET OPTIONS (description = '营业收入，元，累计/YTD'),
ALTER COLUMN total_cogs SET OPTIONS (description = '营业总成本，元，累计/YTD'),
ALTER COLUMN oper_cost SET OPTIONS (description = '营业成本，元，累计/YTD'),
ALTER COLUMN sell_exp SET OPTIONS (description = '销售费用，元，累计/YTD'),
ALTER COLUMN admin_exp SET OPTIONS (description = '管理费用，元，累计/YTD'),
ALTER COLUMN fin_exp SET OPTIONS (description = '财务费用，元，累计/YTD'),
ALTER COLUMN rd_exp SET OPTIONS (description = '研发费用，元，累计/YTD'),
ALTER COLUMN operate_profit SET OPTIONS (description = '营业利润，元，累计/YTD'),
ALTER COLUMN non_oper_income SET OPTIONS (description = '营业外收入，元，累计/YTD'),
ALTER COLUMN non_oper_exp SET OPTIONS (description = '营业外支出，元，累计/YTD'),
ALTER COLUMN total_profit SET OPTIONS (description = '利润总额，元，累计/YTD'),
ALTER COLUMN income_tax SET OPTIONS (description = '所得税费用，元，累计/YTD'),
ALTER COLUMN n_income SET OPTIONS (description = '净利润（含少数股东损益），元，累计/YTD'),
ALTER COLUMN n_income_attr_p SET OPTIONS (description = '归属于母公司股东的净利润，元，累计/YTD'),
ALTER COLUMN minority_gain SET OPTIONS (description = '少数股东损益，元，累计/YTD'),
ALTER COLUMN ebit SET OPTIONS (description = '息税前利润，元，累计/YTD'),
ALTER COLUMN ebitda SET OPTIONS (description = '息税折旧摊销前利润，元，累计/YTD'),
ALTER COLUMN source_system SET OPTIONS (description = '来源系统标识，当前 tushare'),
ALTER COLUMN source_partition_date SET OPTIONS (description = '来源 ODS 分区（报告期），YYYYMMDD 字符串'),
ALTER COLUMN ingested_at SET OPTIONS (description = '来源 ODS 摄入时间'),
ALTER COLUMN report_caliber SET OPTIONS (description = '规范化口径，本表恒为 consolidated'),
ALTER COLUMN is_default_report_caliber SET OPTIONS (description = '是否默认消费口径，本表恒为 TRUE'),
ALTER COLUMN visible_trade_date SET OPTIONS (description = '该版本公告后第一个上交所开市日');

-- ============================================================
-- dwd_fin_balancesheet（资产负债表版本事实表，金额单位元、时点值）
-- ============================================================
ALTER TABLE `data-aquarium.ashare_dwd.dwd_fin_balancesheet`
ALTER COLUMN sec_code SET OPTIONS (description = '证券代码，Tushare ts_code 格式'),
ALTER COLUMN ann_date_eff SET OPTIONS (description = '公告生效日（可见日），COALESCE(f_ann_date, ann_date)，月分区字段'),
ALTER COLUMN report_period SET OPTIONS (description = '报告期，来自 end_date'),
ALTER COLUMN ann_date SET OPTIONS (description = '原始公告日，YYYYMMDD 字符串'),
ALTER COLUMN f_ann_date SET OPTIONS (description = '实际披露/最终公告日，YYYYMMDD 字符串；优先用于 ann_date_eff'),
ALTER COLUMN end_date SET OPTIONS (description = '报告期 YYYYMMDD 字符串原值'),
ALTER COLUMN report_type SET OPTIONS (description = 'Tushare 源报表类型编码，原样保留；1=合并报表（P0 默认消费口径）。实测当前仅 1'),
ALTER COLUMN comp_type SET OPTIONS (description = 'Tushare 公司类型：1 一般工商业 2 银行 3 保险 4 证券 等，决定报表模板'),
ALTER COLUMN update_flag SET OPTIONS (description = 'Tushare 更新标志，同公告时间下优先保留修正版'),
ALTER COLUMN money_cap SET OPTIONS (description = '货币资金，元，时点值'),
ALTER COLUMN accounts_receiv SET OPTIONS (description = '应收账款，元，时点值'),
ALTER COLUMN inventories SET OPTIONS (description = '存货，元，时点值'),
ALTER COLUMN total_cur_assets SET OPTIONS (description = '流动资产合计，元，时点值'),
ALTER COLUMN fix_assets SET OPTIONS (description = '固定资产，元，时点值'),
ALTER COLUMN intan_assets SET OPTIONS (description = '无形资产，元，时点值'),
ALTER COLUMN r_and_d SET OPTIONS (description = '开发支出，元，时点值'),
ALTER COLUMN goodwill SET OPTIONS (description = '商誉，元，时点值'),
ALTER COLUMN total_nca SET OPTIONS (description = '非流动资产合计，元，时点值'),
ALTER COLUMN total_assets SET OPTIONS (description = '资产总计，元，时点值'),
ALTER COLUMN st_borr SET OPTIONS (description = '短期借款，元，时点值'),
ALTER COLUMN lt_borr SET OPTIONS (description = '长期借款，元，时点值'),
ALTER COLUMN total_cur_liab SET OPTIONS (description = '流动负债合计，元，时点值'),
ALTER COLUMN total_ncl SET OPTIONS (description = '非流动负债合计，元，时点值'),
ALTER COLUMN total_liab SET OPTIONS (description = '负债合计，元，时点值'),
ALTER COLUMN minority_int SET OPTIONS (description = '少数股东权益，元，时点值'),
ALTER COLUMN total_hldr_eqy_exc_min_int SET OPTIONS (description = '归属母公司股东权益合计（不含少数股东权益），元，时点值'),
ALTER COLUMN total_hldr_eqy_inc_min_int SET OPTIONS (description = '股东权益合计（含少数股东权益），元，时点值'),
ALTER COLUMN total_liab_hldr_eqy SET OPTIONS (description = '负债及股东权益总计，元，时点值'),
ALTER COLUMN source_system SET OPTIONS (description = '来源系统标识，当前 tushare'),
ALTER COLUMN source_partition_date SET OPTIONS (description = '来源 ODS 分区（报告期），YYYYMMDD 字符串'),
ALTER COLUMN ingested_at SET OPTIONS (description = '来源 ODS 摄入时间'),
ALTER COLUMN report_caliber SET OPTIONS (description = '规范化口径：consolidated/non_consolidated/other/unknown；report_type IS NULL 时为 unknown'),
ALTER COLUMN is_default_report_caliber SET OPTIONS (description = '是否 P0 默认消费口径，等价于 COALESCE(report_type=1, FALSE)'),
ALTER COLUMN visible_trade_date SET OPTIONS (description = '公告生效日之后第一个上交所开市日，用于 PIT as-of join');

-- ============================================================
-- dwd_fin_balancesheet_latest（默认合并口径最新便捷表）
-- ============================================================
ALTER TABLE `data-aquarium.ashare_dwd.dwd_fin_balancesheet_latest`
ALTER COLUMN sec_code SET OPTIONS (description = '证券代码，Tushare ts_code 格式'),
ALTER COLUMN ann_date_eff SET OPTIONS (description = '该报告期默认口径最新版本的公告生效日'),
ALTER COLUMN report_period SET OPTIONS (description = '报告期，(sec_code, report_period) 唯一'),
ALTER COLUMN ann_date SET OPTIONS (description = '原始公告日，YYYYMMDD 字符串'),
ALTER COLUMN f_ann_date SET OPTIONS (description = '实际披露/最终公告日，YYYYMMDD 字符串'),
ALTER COLUMN end_date SET OPTIONS (description = '报告期 YYYYMMDD 字符串原值'),
ALTER COLUMN report_type SET OPTIONS (description = 'Tushare 源报表类型编码，本表恒为 1（合并报表）'),
ALTER COLUMN comp_type SET OPTIONS (description = 'Tushare 公司类型：1 一般工商业 2 银行 3 保险 4 证券 等'),
ALTER COLUMN update_flag SET OPTIONS (description = 'Tushare 更新标志，该报告期取最新修正版'),
ALTER COLUMN money_cap SET OPTIONS (description = '货币资金，元，时点值'),
ALTER COLUMN accounts_receiv SET OPTIONS (description = '应收账款，元，时点值'),
ALTER COLUMN inventories SET OPTIONS (description = '存货，元，时点值'),
ALTER COLUMN total_cur_assets SET OPTIONS (description = '流动资产合计，元，时点值'),
ALTER COLUMN fix_assets SET OPTIONS (description = '固定资产，元，时点值'),
ALTER COLUMN intan_assets SET OPTIONS (description = '无形资产，元，时点值'),
ALTER COLUMN r_and_d SET OPTIONS (description = '开发支出，元，时点值'),
ALTER COLUMN goodwill SET OPTIONS (description = '商誉，元，时点值'),
ALTER COLUMN total_nca SET OPTIONS (description = '非流动资产合计，元，时点值'),
ALTER COLUMN total_assets SET OPTIONS (description = '资产总计，元，时点值'),
ALTER COLUMN st_borr SET OPTIONS (description = '短期借款，元，时点值'),
ALTER COLUMN lt_borr SET OPTIONS (description = '长期借款，元，时点值'),
ALTER COLUMN total_cur_liab SET OPTIONS (description = '流动负债合计，元，时点值'),
ALTER COLUMN total_ncl SET OPTIONS (description = '非流动负债合计，元，时点值'),
ALTER COLUMN total_liab SET OPTIONS (description = '负债合计，元，时点值'),
ALTER COLUMN minority_int SET OPTIONS (description = '少数股东权益，元，时点值'),
ALTER COLUMN total_hldr_eqy_exc_min_int SET OPTIONS (description = '归属母公司股东权益合计（不含少数股东权益），元，时点值'),
ALTER COLUMN total_hldr_eqy_inc_min_int SET OPTIONS (description = '股东权益合计（含少数股东权益），元，时点值'),
ALTER COLUMN total_liab_hldr_eqy SET OPTIONS (description = '负债及股东权益总计，元，时点值'),
ALTER COLUMN source_system SET OPTIONS (description = '来源系统标识，当前 tushare'),
ALTER COLUMN source_partition_date SET OPTIONS (description = '来源 ODS 分区（报告期），YYYYMMDD 字符串'),
ALTER COLUMN ingested_at SET OPTIONS (description = '来源 ODS 摄入时间'),
ALTER COLUMN report_caliber SET OPTIONS (description = '规范化口径，本表恒为 consolidated'),
ALTER COLUMN is_default_report_caliber SET OPTIONS (description = '是否默认消费口径，本表恒为 TRUE'),
ALTER COLUMN visible_trade_date SET OPTIONS (description = '该版本公告后第一个上交所开市日');

-- ============================================================
-- dwd_fin_cashflow（现金流量表版本事实表，金额单位元、累计/YTD）
-- ============================================================
ALTER TABLE `data-aquarium.ashare_dwd.dwd_fin_cashflow`
ALTER COLUMN sec_code SET OPTIONS (description = '证券代码，Tushare ts_code 格式'),
ALTER COLUMN ann_date_eff SET OPTIONS (description = '公告生效日（可见日），COALESCE(f_ann_date, ann_date)，月分区字段'),
ALTER COLUMN report_period SET OPTIONS (description = '报告期，来自 end_date'),
ALTER COLUMN ann_date SET OPTIONS (description = '原始公告日，YYYYMMDD 字符串'),
ALTER COLUMN f_ann_date SET OPTIONS (description = '实际披露/最终公告日，YYYYMMDD 字符串；优先用于 ann_date_eff'),
ALTER COLUMN end_date SET OPTIONS (description = '报告期 YYYYMMDD 字符串原值'),
ALTER COLUMN report_type SET OPTIONS (description = 'Tushare 源报表类型编码，原样保留；1=合并报表（P0 默认消费口径）。实测当前仅 1'),
ALTER COLUMN comp_type SET OPTIONS (description = 'Tushare 公司类型：1 一般工商业 2 银行 3 保险 4 证券 等，决定报表模板'),
ALTER COLUMN update_flag SET OPTIONS (description = 'Tushare 更新标志，同公告时间下优先保留修正版'),
ALTER COLUMN net_profit SET OPTIONS (description = '净利润（现金流量表口径），元，累计/YTD'),
ALTER COLUMN c_fr_sale_sg SET OPTIONS (description = '销售商品、提供劳务收到的现金，元，累计/YTD'),
ALTER COLUMN c_inf_fr_operate_a SET OPTIONS (description = '经营活动现金流入小计，元，累计/YTD'),
ALTER COLUMN c_paid_goods_s SET OPTIONS (description = '购买商品、接受劳务支付的现金，元，累计/YTD'),
ALTER COLUMN st_cash_out_act SET OPTIONS (description = '经营活动现金流出小计，元，累计/YTD'),
ALTER COLUMN n_cashflow_act SET OPTIONS (description = '经营活动产生的现金流量净额，元，累计/YTD'),
ALTER COLUMN n_cashflow_inv_act SET OPTIONS (description = '投资活动产生的现金流量净额，元，累计/YTD'),
ALTER COLUMN stot_cash_in_fnc_act SET OPTIONS (description = '筹资活动现金流入小计，元，累计/YTD'),
ALTER COLUMN n_cash_flows_fnc_act SET OPTIONS (description = '筹资活动产生的现金流量净额，元，累计/YTD'),
ALTER COLUMN free_cashflow SET OPTIONS (description = '企业自由现金流量，元，累计/YTD'),
ALTER COLUMN c_cash_equ_beg_period SET OPTIONS (description = '期初现金及现金等价物余额，元，时点值'),
ALTER COLUMN c_cash_equ_end_period SET OPTIONS (description = '期末现金及现金等价物余额，元，时点值'),
ALTER COLUMN n_incr_cash_cash_equ SET OPTIONS (description = '现金及现金等价物净增加额，元，累计/YTD'),
ALTER COLUMN source_system SET OPTIONS (description = '来源系统标识，当前 tushare'),
ALTER COLUMN source_partition_date SET OPTIONS (description = '来源 ODS 分区（报告期），YYYYMMDD 字符串'),
ALTER COLUMN ingested_at SET OPTIONS (description = '来源 ODS 摄入时间'),
ALTER COLUMN report_caliber SET OPTIONS (description = '规范化口径：consolidated/non_consolidated/other/unknown；report_type IS NULL 时为 unknown'),
ALTER COLUMN is_default_report_caliber SET OPTIONS (description = '是否 P0 默认消费口径，等价于 COALESCE(report_type=1, FALSE)'),
ALTER COLUMN visible_trade_date SET OPTIONS (description = '公告生效日之后第一个上交所开市日，用于 PIT as-of join');

-- ============================================================
-- dwd_fin_cashflow_latest（默认合并口径最新便捷表）
-- ============================================================
ALTER TABLE `data-aquarium.ashare_dwd.dwd_fin_cashflow_latest`
ALTER COLUMN sec_code SET OPTIONS (description = '证券代码，Tushare ts_code 格式'),
ALTER COLUMN ann_date_eff SET OPTIONS (description = '该报告期默认口径最新版本的公告生效日'),
ALTER COLUMN report_period SET OPTIONS (description = '报告期，(sec_code, report_period) 唯一'),
ALTER COLUMN ann_date SET OPTIONS (description = '原始公告日，YYYYMMDD 字符串'),
ALTER COLUMN f_ann_date SET OPTIONS (description = '实际披露/最终公告日，YYYYMMDD 字符串'),
ALTER COLUMN end_date SET OPTIONS (description = '报告期 YYYYMMDD 字符串原值'),
ALTER COLUMN report_type SET OPTIONS (description = 'Tushare 源报表类型编码，本表恒为 1（合并报表）'),
ALTER COLUMN comp_type SET OPTIONS (description = 'Tushare 公司类型：1 一般工商业 2 银行 3 保险 4 证券 等'),
ALTER COLUMN update_flag SET OPTIONS (description = 'Tushare 更新标志，该报告期取最新修正版'),
ALTER COLUMN net_profit SET OPTIONS (description = '净利润（现金流量表口径），元，累计/YTD'),
ALTER COLUMN c_fr_sale_sg SET OPTIONS (description = '销售商品、提供劳务收到的现金，元，累计/YTD'),
ALTER COLUMN c_inf_fr_operate_a SET OPTIONS (description = '经营活动现金流入小计，元，累计/YTD'),
ALTER COLUMN c_paid_goods_s SET OPTIONS (description = '购买商品、接受劳务支付的现金，元，累计/YTD'),
ALTER COLUMN st_cash_out_act SET OPTIONS (description = '经营活动现金流出小计，元，累计/YTD'),
ALTER COLUMN n_cashflow_act SET OPTIONS (description = '经营活动产生的现金流量净额，元，累计/YTD'),
ALTER COLUMN n_cashflow_inv_act SET OPTIONS (description = '投资活动产生的现金流量净额，元，累计/YTD'),
ALTER COLUMN stot_cash_in_fnc_act SET OPTIONS (description = '筹资活动现金流入小计，元，累计/YTD'),
ALTER COLUMN n_cash_flows_fnc_act SET OPTIONS (description = '筹资活动产生的现金流量净额，元，累计/YTD'),
ALTER COLUMN free_cashflow SET OPTIONS (description = '企业自由现金流量，元，累计/YTD'),
ALTER COLUMN c_cash_equ_beg_period SET OPTIONS (description = '期初现金及现金等价物余额，元，时点值'),
ALTER COLUMN c_cash_equ_end_period SET OPTIONS (description = '期末现金及现金等价物余额，元，时点值'),
ALTER COLUMN n_incr_cash_cash_equ SET OPTIONS (description = '现金及现金等价物净增加额，元，累计/YTD'),
ALTER COLUMN source_system SET OPTIONS (description = '来源系统标识，当前 tushare'),
ALTER COLUMN source_partition_date SET OPTIONS (description = '来源 ODS 分区（报告期），YYYYMMDD 字符串'),
ALTER COLUMN ingested_at SET OPTIONS (description = '来源 ODS 摄入时间'),
ALTER COLUMN report_caliber SET OPTIONS (description = '规范化口径，本表恒为 consolidated'),
ALTER COLUMN is_default_report_caliber SET OPTIONS (description = '是否默认消费口径，本表恒为 TRUE'),
ALTER COLUMN visible_trade_date SET OPTIONS (description = '该版本公告后第一个上交所开市日');

-- ============================================================
-- dws_stock_feature_fin_daily（默认合并口径 PIT 财务特征宽表）
-- ============================================================
ALTER TABLE `data-aquarium.ashare_dws.dws_stock_feature_fin_daily`
ALTER COLUMN trade_date SET OPTIONS (description = '交易日，月分区字段'),
ALTER COLUMN sec_code SET OPTIONS (description = '统一证券代码，Tushare ts_code 格式'),
ALTER COLUMN feature_version SET OPTIONS (description = '财务特征版本'),
ALTER COLUMN report_period SET OPTIONS (description = '主报告期（利润表 as-of 选中的报告期）；无可见财报时为空'),
ALTER COLUMN ann_date_eff SET OPTIONS (description = '主报告期被选中版本的公告生效日'),
ALTER COLUMN visible_trade_date SET OPTIONS (description = '主报告期被选中版本的可见交易日，PIT 防线：恒 <= trade_date'),
ALTER COLUMN report_caliber SET OPTIONS (description = '消费口径契约：三大报表恒为 consolidated（默认合并口径）'),
ALTER COLUMN is_default_report_caliber SET OPTIONS (description = '消费口径契约：恒为 TRUE，三大报表特征只来自默认合并口径；可用性见 has_fin_*'),
ALTER COLUMN report_age_days SET OPTIONS (description = 'trade_date 与主报告期之差（天），财务新鲜度'),
ALTER COLUMN fin_report_lag_days SET OPTIONS (description = '主报告期可见交易日与报告期之差（天），披露时滞'),
ALTER COLUMN has_fin_indicator SET OPTIONS (description = '该交易日是否有可见的 fina_indicator 版本'),
ALTER COLUMN has_fin_income SET OPTIONS (description = '该交易日是否有可见的默认口径利润表'),
ALTER COLUMN has_fin_balancesheet SET OPTIONS (description = '该交易日是否有可见的默认口径资产负债表'),
ALTER COLUMN has_fin_cashflow SET OPTIONS (description = '该交易日是否有可见的默认口径现金流量表'),
ALTER COLUMN ind_report_caliber SET OPTIONS (description = 'fina_indicator 口径标识，恒为 source_default（源无 report_type）'),
ALTER COLUMN ind_report_period SET OPTIONS (description = 'fina_indicator as-of 选中的报告期'),
ALTER COLUMN ind_visible_trade_date SET OPTIONS (description = 'fina_indicator 选中版本可见交易日，恒 <= trade_date'),
ALTER COLUMN bs_report_period SET OPTIONS (description = '资产负债表 as-of 选中的报告期'),
ALTER COLUMN bs_visible_trade_date SET OPTIONS (description = '资产负债表选中版本可见交易日，恒 <= trade_date'),
ALTER COLUMN cf_report_period SET OPTIONS (description = '现金流量表 as-of 选中的报告期'),
ALTER COLUMN cf_visible_trade_date SET OPTIONS (description = '现金流量表选中版本可见交易日，恒 <= trade_date'),
ALTER COLUMN roe SET OPTIONS (description = '净资产收益率（fina_indicator），百分比，as-of PIT'),
ALTER COLUMN roe_deducted SET OPTIONS (description = '扣非净资产收益率（fina_indicator），百分比，as-of PIT'),
ALTER COLUMN roa SET OPTIONS (description = '总资产收益率（fina_indicator），百分比，as-of PIT'),
ALTER COLUMN roic SET OPTIONS (description = '投入资本回报率（fina_indicator），百分比，as-of PIT'),
ALTER COLUMN grossprofit_margin SET OPTIONS (description = '销售毛利率（fina_indicator），百分比，as-of PIT'),
ALTER COLUMN netprofit_margin SET OPTIONS (description = '销售净利率（fina_indicator），百分比，as-of PIT'),
ALTER COLUMN debt_to_assets SET OPTIONS (description = '资产负债率（fina_indicator），百分比，as-of PIT'),
ALTER COLUMN current_ratio SET OPTIONS (description = '流动比率（fina_indicator），比例，as-of PIT'),
ALTER COLUMN quick_ratio SET OPTIONS (description = '速动比率（fina_indicator），比例，as-of PIT'),
ALTER COLUMN assets_to_equity SET OPTIONS (description = '权益乘数（fina_indicator），比例，as-of PIT'),
ALTER COLUMN ocf_to_or SET OPTIONS (description = '经营现金流量净额/营业收入（fina_indicator），比例，as-of PIT'),
ALTER COLUMN ocf_to_profit SET OPTIONS (description = '经营现金流量净额/净利润（fina_indicator），比例，as-of PIT'),
ALTER COLUMN cash_ratio SET OPTIONS (description = '现金比率（fina_indicator），比例，as-of PIT'),
ALTER COLUMN netprofit_yoy SET OPTIONS (description = '净利润同比增速（fina_indicator），百分比，as-of PIT'),
ALTER COLUMN operating_revenue_yoy SET OPTIONS (description = '营业收入同比增速（fina_indicator），百分比，as-of PIT'),
ALTER COLUMN total_revenue_yoy SET OPTIONS (description = '营业总收入同比增速（fina_indicator），百分比，as-of PIT'),
ALTER COLUMN basic_eps_yoy SET OPTIONS (description = '基本每股收益同比增速（fina_indicator），百分比，as-of PIT'),
ALTER COLUMN q_roe SET OPTIONS (description = '单季度净资产收益率（fina_indicator），百分比，as-of PIT'),
ALTER COLUMN q_netprofit_margin SET OPTIONS (description = '单季度销售净利率（fina_indicator），百分比，as-of PIT'),
ALTER COLUMN q_grossprofit_margin SET OPTIONS (description = '单季度销售毛利率（fina_indicator），百分比，as-of PIT'),
ALTER COLUMN total_revenue SET OPTIONS (description = '营业总收入，元，累计/YTD（利润表 as-of）'),
ALTER COLUMN revenue SET OPTIONS (description = '营业收入，元，累计/YTD（利润表 as-of）'),
ALTER COLUMN operate_profit SET OPTIONS (description = '营业利润，元，累计/YTD（利润表 as-of）'),
ALTER COLUMN total_profit SET OPTIONS (description = '利润总额，元，累计/YTD（利润表 as-of）'),
ALTER COLUMN n_income SET OPTIONS (description = '净利润（含少数股东损益），元，累计/YTD（利润表 as-of）'),
ALTER COLUMN n_income_attr_p SET OPTIONS (description = '归母净利润，元，累计/YTD（利润表 as-of）'),
ALTER COLUMN ebit SET OPTIONS (description = '息税前利润，元，累计/YTD（利润表 as-of）'),
ALTER COLUMN ebitda SET OPTIONS (description = '息税折旧摊销前利润，元，累计/YTD（利润表 as-of）'),
ALTER COLUMN basic_eps SET OPTIONS (description = '基本每股收益，元/股（利润表 as-of）'),
ALTER COLUMN total_assets SET OPTIONS (description = '资产总计，元，时点值（资产负债表 as-of）'),
ALTER COLUMN total_cur_assets SET OPTIONS (description = '流动资产合计，元，时点值（资产负债表 as-of）'),
ALTER COLUMN total_cur_liab SET OPTIONS (description = '流动负债合计，元，时点值（资产负债表 as-of）'),
ALTER COLUMN total_liab SET OPTIONS (description = '负债合计，元，时点值（资产负债表 as-of）'),
ALTER COLUMN total_hldr_eqy_exc_min_int SET OPTIONS (description = '归母股东权益合计，元，时点值（资产负债表 as-of）'),
ALTER COLUMN total_hldr_eqy_inc_min_int SET OPTIONS (description = '股东权益合计（含少数股东权益），元，时点值（资产负债表 as-of）'),
ALTER COLUMN minority_int SET OPTIONS (description = '少数股东权益，元，时点值（资产负债表 as-of）'),
ALTER COLUMN money_cap SET OPTIONS (description = '货币资金，元，时点值（资产负债表 as-of）'),
ALTER COLUMN inventories SET OPTIONS (description = '存货，元，时点值（资产负债表 as-of）'),
ALTER COLUMN accounts_receiv SET OPTIONS (description = '应收账款，元，时点值（资产负债表 as-of）'),
ALTER COLUMN goodwill SET OPTIONS (description = '商誉，元，时点值（资产负债表 as-of）'),
ALTER COLUMN n_cashflow_act SET OPTIONS (description = '经营活动现金流量净额，元，累计/YTD（现金流量表 as-of）'),
ALTER COLUMN n_cashflow_inv_act SET OPTIONS (description = '投资活动现金流量净额，元，累计/YTD（现金流量表 as-of）'),
ALTER COLUMN n_cash_flows_fnc_act SET OPTIONS (description = '筹资活动现金流量净额，元，累计/YTD（现金流量表 as-of）'),
ALTER COLUMN free_cashflow SET OPTIONS (description = '企业自由现金流量，元，累计/YTD（现金流量表 as-of）'),
ALTER COLUMN cf_net_profit SET OPTIONS (description = '净利润（现金流量表口径），元，累计/YTD（现金流量表 as-of）'),
ALTER COLUMN created_at SET OPTIONS (description = '本表构建时间戳');
