steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - orchestration/workflows/Dockerfile.pipeline_control
      - -t
      - ${_IMAGE_URI}
      - .
images:
  - ${_IMAGE_URI}

