#!/usr/bin/env python3
"""Generate BigQuery ODS index external-table URI SQL from the ingestion manifest."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_CONFIG = REPO_ROOT / "configs/ingestion/ods_current_scope_v0.yml"
DEFAULT_OUTPUT = REPO_ROOT / "sql/ods/01_index_external_table_uris.sql"

TABLE_DEFINITIONS = {
    "index_daily": {
        "table": "data-aquarium.ashare_ods.ods_tushare_index_daily",
        "description": "获取指数每日行情，还可以通过bar接口获取。由于服务器压力，目前规则是单次调取最多取8000行记录，可以设置start和end日期补全。指数行情也可以通过 通用行情接口 获取数据。本接口不包含 申万行业指数行情数据。\\nODS实际分区起始：1991-04-03（partition_date=19910403）。\\nTushare官方口径：全部历史（官方文档 doc_id=108; doc_id=95）。",
    },
    "index_dailybasic": {
        "table": "data-aquarium.ashare_ods.ods_tushare_index_dailybasic",
        "description": "目前只提供上证综指，深证成指，上证50，中证500，中小板指，创业板指的每日指标数据\\nODS实际分区起始：2004-01-02（partition_date=20040102）。\\nTushare官方口径：从2004年1月开始提供 数据权（官方文档 doc_id=128）。",
    },
}


def load_manifest(path: Path) -> dict:
    with path.open("r", encoding="utf-8") as handle:
        data = yaml.safe_load(handle)
    if not isinstance(data, dict):
        raise ValueError(f"Manifest must be a mapping: {path}")
    return data


def endpoint_entry(manifest: dict, endpoint: str) -> dict:
    for entry in manifest.get("endpoints", []):
        if entry.get("endpoint") == endpoint:
            return entry
    raise ValueError(f"Missing endpoint in manifest: {endpoint}")


def variant_partition_endpoints(entry: dict) -> list[str]:
    variants = entry.get("request_variants") or []
    endpoints: list[str] = []
    for variant in variants:
        partition_endpoint = variant.get("partition_endpoint") or variant.get("variant")
        if not partition_endpoint:
            raise ValueError(f"Variant missing partition_endpoint: {variant}")
        endpoints.append(str(partition_endpoint))
    if not endpoints:
        raise ValueError(f"Endpoint has no request_variants: {entry.get('endpoint')}")
    if len(endpoints) != len(set(endpoints)):
        raise ValueError(f"Duplicate partition_endpoint values for {entry.get('endpoint')}: {endpoints}")
    return endpoints


def quote_sql_string(value: str) -> str:
    return "'" + value.replace("'", "\\'") + "'"


def render_table(api: str, entry: dict) -> str:
    definition = TABLE_DEFINITIONS[api]
    table = definition["table"]
    description = quote_sql_string(definition["description"])
    bucket = entry.get("gcs_bucket") or "data-aquarium"
    endpoints = variant_partition_endpoints(entry)
    uri_lines = []
    for index, partition_endpoint in enumerate(endpoints):
        comma = "," if index < len(endpoints) - 1 else ""
        uri = f"gs://{bucket}/a-share/tushare/raw_data/api={api}/endpoint={partition_endpoint}/partition_date=*/data.parquet"
        uri_lines.append(f"    {quote_sql_string(uri)}{comma}")
    uris = "\n".join(uri_lines)
    return f"""CREATE OR REPLACE EXTERNAL TABLE `{table}`
WITH PARTITION COLUMNS (
  endpoint STRING,
  partition_date STRING
)
OPTIONS (
  description = {description},
  format = 'PARQUET',
  hive_partition_uri_prefix = 'gs://{bucket}/a-share/tushare/raw_data/api={api}/',
  require_hive_partition_filter = TRUE,
  uris = [
{uris}
  ]
);"""


def render_sql(manifest: dict) -> str:
    daily = endpoint_entry(manifest, "index_daily")
    dailybasic = endpoint_entry(manifest, "index_dailybasic")
    return "\n".join(
        [
            "-- 文档维护：GPT-5 Codex（最近更新 2026-06-08）",
            "-- BigQuery Standard SQL",
            "-- Generated by scripts/ingestion/generate_index_external_table_uris.py.",
            "-- Source manifest: configs/ingestion/ods_current_scope_v0.yml.",
            "-- Run with --check in CI/review to ensure all configured index endpoint variants are exposed to BigQuery ODS.",
            "",
            render_table("index_daily", daily),
            "",
            render_table("index_dailybasic", dailybasic),
            "",
        ]
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", type=Path, default=DEFAULT_CONFIG)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true", help="fail if output is not up to date")
    args = parser.parse_args(argv)

    manifest = load_manifest(args.config)
    rendered = render_sql(manifest)

    if args.check:
        existing = args.output.read_text(encoding="utf-8") if args.output.exists() else ""
        if existing != rendered:
            print(f"{args.output} is not generated from {args.config}; run this script without --check", file=sys.stderr)
            return 1
        return 0

    args.output.write_text(rendered, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
